"""Self-consolidating wiki merger using an LLM consensus loop."""
from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger("rekipedia.wiki_merger")

_MERGE_SYSTEM_PROMPT = """\
You are an expert technical editor. Your task is to merge newly generated documentation with an existing wiki page.
The existing page might contain custom developer annotations, Architecture Decision Records (ADRs), or manually added notes.
The new page contains updated function signatures, file descriptions, and latest static-analysis summaries from the codebase.

## CRITICAL RULES:
1. PRESERVE all manual developer annotations, warnings, custom markdown paragraphs, notes, or comments from the existing page.
2. UPDATE any code sections, function lists, directory tables, or static analysis results with the information from the new page.
3. DO NOT duplicate sections or paragraphs.
4. Maintain a clean, coherent, and cohesive markdown layout with proper frontmatter.
5. If the existing page has frontmatter, preserve it or merge it appropriately.
6. Return only the final merged markdown page content (including the frontmatter). Do not include any explanation or commentary outside the markdown.
"""


def merge_wiki_pages(
    llm_client: Any,
    slug: str,
    existing_content: str,
    new_content: str,
) -> str:
    """Consolidate the existing wiki page and new content using LLM."""
    if not existing_content.strip():
        return new_content

    user_prompt = (
        f"### EXISTING WIKI PAGE (may contain manual developer notes):\n"
        f"```markdown\n{existing_content}\n```\n\n"
        f"### NEW AUTOGENERATED WIKI PAGE (contains updated signatures and static facts):\n"
        f"```markdown\n{new_content}\n```\n\n"
        f"Merge the two pages according to the critical rules."
    )

    try:
        raw = llm_client.call(user_prompt, system=_MERGE_SYSTEM_PROMPT, timeout=120)
        return raw.strip()
    except Exception as e:
        logger.error(f"Failed to semantically merge wiki page '{slug}': {e}. Falling back to new content.")
        return new_content
