"""OKF (Open Knowledge Format) exporter for rekipedia wikis.

Produces a standards-compliant OKF v0.1 Knowledge Bundle:
- wiki/<slug>.md  — OKF Concept Documents with YAML frontmatter
- diagrams/<slug>.md  — OKF diagram pages
- index.md  — bundle directory listing (OKF §6)
- log.md    — export history (OKF §7)

Spec: https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md
"""
from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml


_BUNDLE_INDEX_HEADER = """\
---
type: rekipedia/bundle-index
title: "{title} — Knowledge Bundle"
description: "OKF v0.1 Knowledge Bundle generated by rekipedia."
tags: [index, rekipedia]
timestamp: "{timestamp}"
---

# {title} — Knowledge Bundle

This bundle was generated by [rekipedia](https://github.com/unrealandychan/rekipedia)
and conforms to the [Open Knowledge Format (OKF) v0.1](https://github.com/GoogleCloudPlatform/knowledge-catalog/blob/main/okf/SPEC.md).

"""


def _to_okf_frontmatter(meta: dict[str, Any]) -> dict[str, Any]:
    """Map rekipedia page metadata to OKF v0.1 frontmatter fields.

    Args:
        meta: Page metadata dict containing rekipedia fields.

    Returns:
        OKF-compliant frontmatter dict.
    """
    slug = meta.get("slug", "")
    return {
        "type": "rekipedia/wiki-page",
        "title": meta.get("title", slug.replace("-", " ").title()),
        "description": meta.get("description", ""),
        "resource": f"wiki/{slug}.md",
        "tags": meta.get("tags") or [],
        "timestamp": meta.get("created_at", datetime.now(UTC).isoformat()),
    }


def _extract_description(body: str) -> str:
    """Extract the first meaningful non-heading line as OKF description.

    Args:
        body: Markdown body text.

    Returns:
        First non-empty, non-heading line (max 200 chars).
    """
    for line in body.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("---"):
            return stripped[:200]
    return ""


def _strip_reki_frontmatter(content: str) -> tuple[dict, str]:
    """Split rekipedia wiki page content into frontmatter dict and body.

    Args:
        content: Full page content including optional YAML frontmatter.

    Returns:
        Tuple of (frontmatter_dict, body_str).
    """
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    fm_str = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")
    try:
        fm = yaml.safe_load(fm_str) or {}
    except Exception:
        fm = {}
    return fm, body


def _write_okf_page(content: str, meta: dict, dest: Path) -> None:
    """Write a single OKF Concept Document with OKF frontmatter.

    Strips rekipedia-specific frontmatter and replaces with OKF fields.

    Args:
        content: Original wiki page content.
        meta: Page metadata dict from manifest.
        dest: Destination file path.
    """
    reki_fm, body = _strip_reki_frontmatter(content)
    merged = {**meta, **reki_fm}
    okf_fm = _to_okf_frontmatter(merged)
    if not okf_fm["description"]:
        okf_fm["description"] = _extract_description(body)
    fm_str = yaml.dump(okf_fm, allow_unicode=True, sort_keys=False, default_flow_style=False)
    dest.write_text(f"---\n{fm_str}---\n\n{body}", encoding="utf-8")


class OkfExporter:
    """Export a rekipedia wiki as an OKF v0.1 Knowledge Bundle directory.

    Usage:
        exporter = OkfExporter(wiki_dir, diagrams_dir, repo_root)
        summary = exporter.export(output_dir, pages_meta=pages_meta)
    """

    def __init__(self, wiki_dir: Path, diagrams_dir: Path, repo_root: Path) -> None:
        self.wiki_dir = Path(wiki_dir)
        self.diagrams_dir = Path(diagrams_dir)
        self.repo_root = Path(repo_root)

    def export(
        self,
        output_dir: Path,
        pages_meta: dict[str, dict] | None = None,
    ) -> dict[str, Any]:
        """Write OKF bundle to output_dir.

        Args:
            output_dir: Destination directory for the OKF bundle.
            pages_meta: Optional dict of {slug: metadata} from manifest.json.

        Returns:
            Summary dict with keys: pages (list[str]), diagrams (list[str]),
            bundle_dir (str).
        """
        output_dir = Path(output_dir)
        wiki_out = output_dir / "wiki"
        diagrams_out = output_dir / "diagrams"
        wiki_out.mkdir(parents=True, exist_ok=True)
        diagrams_out.mkdir(parents=True, exist_ok=True)
        pages_meta = pages_meta or {}
        now = datetime.now(UTC).isoformat()

        written_pages: list[str] = []
        written_diagrams: list[str] = []

        # Export wiki pages as OKF Concept Documents
        if self.wiki_dir.exists():
            for md_file in sorted(self.wiki_dir.glob("*.md")):
                slug = md_file.stem
                content = md_file.read_text(encoding="utf-8")
                meta = dict(pages_meta.get(slug, {}))
                meta["slug"] = slug
                dest = wiki_out / md_file.name
                _write_okf_page(content, meta, dest)
                written_pages.append(slug)

        # Export diagrams with OKF type: rekipedia/diagram
        if self.diagrams_dir.exists():
            for md_file in sorted(self.diagrams_dir.glob("*.md")):
                slug = md_file.stem
                content = md_file.read_text(encoding="utf-8")
                fm: dict[str, Any] = {
                    "type": "rekipedia/diagram",
                    "title": slug.replace("-", " ").title(),
                    "description": f"Mermaid diagram: {slug}",
                    "resource": f"diagrams/{slug}.md",
                    "tags": ["diagram"],
                    "timestamp": now,
                }
                fm_str = yaml.dump(fm, allow_unicode=True, sort_keys=False, default_flow_style=False)
                dest = diagrams_out / md_file.name
                dest.write_text(f"---\n{fm_str}---\n\n{content}", encoding="utf-8")
                written_diagrams.append(slug)

        # Write bundle index.md (OKF §6 — directory listing)
        self._write_bundle_index(output_dir, written_pages, written_diagrams, pages_meta, now)

        # Write log.md (OKF §7 — export history)
        self._write_export_log(output_dir, written_pages, written_diagrams, now)

        return {
            "pages": written_pages,
            "diagrams": written_diagrams,
            "bundle_dir": str(output_dir),
        }

    def _write_bundle_index(
        self,
        output_dir: Path,
        pages: list[str],
        diagrams: list[str],
        pages_meta: dict[str, dict],
        timestamp: str,
    ) -> None:
        """Write OKF §6 bundle index.md listing all concepts."""
        header = _BUNDLE_INDEX_HEADER.format(
            title=self.repo_root.name.replace("-", " ").title(),
            timestamp=timestamp,
        )
        lines = [header, "## Wiki Pages\n\n"]
        for slug in pages:
            meta = pages_meta.get(slug, {})
            title = meta.get("title", slug.replace("-", " ").title())
            tags = meta.get("tags") or []
            tag_str = f" — `{'`, `'.join(tags)}`" if tags else ""
            lines.append(f"- [{title}](wiki/{slug}.md){tag_str}\n")

        if diagrams:
            lines.append("\n## Diagrams\n\n")
            for slug in diagrams:
                lines.append(f"- [{slug.replace('-', ' ').title()}](diagrams/{slug}.md)\n")

        (output_dir / "index.md").write_text("".join(lines), encoding="utf-8")

    def _write_export_log(
        self,
        output_dir: Path,
        pages: list[str],
        diagrams: list[str],
        timestamp: str,
    ) -> None:
        """Write or prepend to OKF §7 log.md."""
        entry = (
            f"## {timestamp}\n\n"
            f"OKF bundle exported by rekipedia from `{self.repo_root.name}`.\n\n"
            f"- {len(pages)} wiki pages\n"
            f"- {len(diagrams)} diagrams\n\n"
        )
        log_path = output_dir / "log.md"
        if log_path.exists():
            existing = log_path.read_text(encoding="utf-8")
            if existing.startswith("# Knowledge Bundle Changelog"):
                header, rest = existing.split("\n", 1)
                log_path.write_text(f"{header}\n\n{entry}{rest.lstrip()}", encoding="utf-8")
            else:
                log_path.write_text(entry + existing, encoding="utf-8")
        else:
            log_path.write_text(f"# Knowledge Bundle Changelog\n\n{entry}", encoding="utf-8")
