"""Generate per-section index pages for progressive disclosure (OKF §6 pattern).

Produces one `index-<section>.md` file per unique section group found in the
wiki pages metadata. Each index lists all pages in that section with links.
"""
from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any


_SECTION_INDEX_TEMPLATE = """\
---
type: rekipedia/section-index
title: "{section_title}"
description: "Index of {count} pages in the '{section}' section."
tags:
  - index
  - {section}
---

# {section_title}

Section index for the **{section}** category.

## Pages

{page_list}

---
*Generated by [rekipedia](https://github.com/unrealandychan/rekipedia). Do not edit manually.*
"""


def write_section_indexes(
    wiki_dir: Path,
    pages_meta: list[dict[str, Any]],
) -> dict[str, Any]:
    """Write one `index-<section>.md` per section into wiki_dir.

    Only writes index files for pages that have a non-empty `section` field.
    Files are named `index-<section>.md` to avoid collision with real wiki pages.

    Args:
        wiki_dir: Path to the .rekipedia/wiki/ directory.
        pages_meta: List of page metadata dicts (from manifest.json pages list).
            Each dict should have at minimum: slug, title. Optional: section, tags.

    Returns:
        Dict with key "sections": {section_name: page_count}
    """
    wiki_dir = Path(wiki_dir)
    sections: dict[str, list[dict]] = defaultdict(list)

    for meta in pages_meta:
        section = (meta.get("section") or "").strip()
        if not section:
            continue
        sections[section].append(meta)

    written: dict[str, int] = {}
    for section, pages in sorted(sections.items()):
        section_title = section.replace("-", " ").replace("_", " ").title()
        page_lines: list[str] = []
        for page in sorted(pages, key=lambda p: (p.get("title") or p["slug"]).lower()):
            slug = page["slug"]
            title = page.get("title") or slug.replace("-", " ").title()
            tags = page.get("tags") or []
            tag_str = f" — `{'`, `'.join(tags)}`" if tags else ""
            page_lines.append(f"- [{title}]({slug}.md){tag_str}")

        content = _SECTION_INDEX_TEMPLATE.format(
            section=section,
            section_title=section_title,
            count=len(pages),
            page_list="\n".join(page_lines),
        )
        dest = wiki_dir / f"index-{section}.md"
        dest.write_text(content, encoding="utf-8")
        written[section] = len(pages)

    return {"sections": written}
