package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var contextFlags struct {
	repo      string
	output    string
	maxTokens int
}

var contextCmd = &cobra.Command{
	Use:   "context",
	Short: "Generate an agent-ready single-file context document from the wiki",
	Long: `Read .rekipedia/wiki/*.md files and produce a condensed Markdown context
document suitable for use as an AI agent's single-file context payload.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		repoPath, err := filepath.Abs(contextFlags.repo)
		if err != nil {
			return fmt.Errorf("resolve repo path: %w", err)
		}

		rekiDir := filepath.Join(repoPath, ".rekipedia")
		wikiDir := filepath.Join(rekiDir, "wiki")

		now := time.Now().UTC().Format("2006-01-02T15:04:05Z")
		repoName := filepath.Base(repoPath)

		var sb strings.Builder

		// Frontmatter
		sb.WriteString("---\n")
		fmt.Fprintf(&sb, "generated_at: %s\n", now)
		fmt.Fprintf(&sb, "repo: %s\n", repoPath)
		fmt.Fprintf(&sb, "max_tokens: %d\n", contextFlags.maxTokens)
		sb.WriteString("source: rekipedia context\n")
		sb.WriteString("---\n\n")

		fmt.Fprintf(&sb, "# rekipedia context: %s\n\n", repoName)
		sb.WriteString("> This document was generated by `rekipedia context` and is intended for " +
			"use as a single-file context payload for AI agents.\n\n")

		// Wiki pages
		sb.WriteString("## Wiki Pages\n\n")
		pageCount := 0
		entries, err := os.ReadDir(wikiDir)
		if err == nil {
			for _, e := range entries {
				if e.IsDir() {
					continue
				}
				name := e.Name()
				if !strings.HasSuffix(name, ".md") {
					continue
				}
				slug := strings.TrimSuffix(name, ".md")
				title := toTitle(slug)
				data, readErr := os.ReadFile(filepath.Join(wikiDir, name))
				if readErr != nil {
					continue
				}
				content := strings.TrimSpace(string(data))
				fmt.Fprintf(&sb, "### %s\n\n%s\n\n---\n\n", title, content)
				pageCount++
			}
		}
		if pageCount == 0 {
			sb.WriteString("*No wiki pages found. Run `rekipedia scan` first.*\n\n")
		}

		// Truncate to max tokens
		maxChars := contextFlags.maxTokens * 4
		full := sb.String()
		if len(full) > maxChars {
			notice := fmt.Sprintf("\n\n---\n*Context truncated to %d tokens (%d chars). Total available: %d chars.*\n",
				contextFlags.maxTokens, maxChars, len(full))
			full = full[:maxChars-len(notice)] + notice
		}

		// Write output
		dest := contextFlags.output
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return fmt.Errorf("create output dir: %w", err)
		}
		if err := os.WriteFile(dest, []byte(full), 0o644); err != nil {
			return fmt.Errorf("write context file: %w", err)
		}

		stat, _ := os.Stat(dest)
		sizeKB := 0.0
		if stat != nil {
			sizeKB = float64(stat.Size()) / 1024
		}
		tokenEst := len(full) / 4
		fmt.Fprintf(os.Stderr, "✅ Context written → %s (%.1f KB, ~%d tokens)\n", dest, sizeKB, tokenEst)
		fmt.Fprintf(os.Stderr, "   wiki pages : %d\n", pageCount)
		return nil
	},
}

// toTitle converts a slug like "my-page" to "My Page".
func toTitle(slug string) string {
	parts := strings.Split(slug, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

func init() {
	contextCmd.Flags().StringVar(&contextFlags.repo, "repo", ".", "Root of the repository")
	contextCmd.Flags().StringVar(&contextFlags.output, "output", "context.md", "Destination file path")
	contextCmd.Flags().IntVar(&contextFlags.maxTokens, "max-tokens", 32000, "Maximum token budget (~4 chars/token)")
}
