package cmd

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pterm/pterm"
	"github.com/spf13/cobra"
)

var refactorFlags struct {
	noLLM     bool
	toStdout  bool
	severity  string
	outputJSON bool
	model     string
	outputDir string
	noDocker  bool
	verbose   bool
	languages string
}

// annotationPattern matches TODO/FIXME/HACK/XXX/BUG/NOTE inline comments
// in common source languages that use # or // style comments.
var annotationPattern = regexp.MustCompile(`(?i)(?://|#)\s*(TODO|FIXME|HACK|XXX|BUG|NOTE)\b[:\s]*(.*)`)

var skipDirs = map[string]bool{
	".git": true, ".rekipedia": true, "node_modules": true,
	"__pycache__": true, ".venv": true, "venv": true,
	"dist": true, "build": true, ".mypy_cache": true,
}

var textExtensions = map[string]bool{
	".py": true, ".go": true, ".ts": true, ".tsx": true,
	".js": true, ".jsx": true, ".java": true, ".cs": true,
	".cpp": true, ".c": true, ".h": true, ".hpp": true,
	".rb": true, ".rs": true, ".swift": true, ".kt": true,
	".php": true, ".sh": true, ".yaml": true, ".yml": true,
	".toml": true, ".json": true, ".md": true,
}

var severityOrder = []string{"critical", "high", "medium", "low"}

var severityEmoji = map[string]string{
	"critical": "🔴",
	"high":     "🟠",
	"medium":   "🟡",
	"low":      "🟢",
}

// Finding holds a single code-quality annotation found during static walk.
type Finding struct {
	Type        string `json:"type"`
	Severity    string `json:"severity"`
	File        string `json:"file"`
	Line        int    `json:"line"`
	Description string `json:"description"`
}

func severityIndex(s string) int {
	for i, v := range severityOrder {
		if v == s {
			return i
		}
	}
	return len(severityOrder)
}

// staticWalk walks repoRoot and collects annotation findings.
func staticWalk(repoRoot string) ([]Finding, error) {
	var findings []Finding
	err := filepath.Walk(repoRoot, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil //nolint:nilerr // skip unreadable entries
		}
		base := filepath.Base(path)
		if info.IsDir() {
			if skipDirs[base] {
				return filepath.SkipDir
			}
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if !textExtensions[ext] {
			return nil
		}
		rel, _ := filepath.Rel(repoRoot, path)
		f, err := os.Open(path)
		if err != nil {
			return nil //nolint:nilerr
		}
		defer f.Close()
		scanner := bufio.NewScanner(f)
		lineNum := 0
		for scanner.Scan() {
			lineNum++
			line := scanner.Text()
			m := annotationPattern.FindStringSubmatch(line)
			if m == nil {
				continue
			}
			tag := strings.ToUpper(m[1])
			desc := strings.TrimSpace(m[2])
			if desc == "" {
				desc = tag + " comment"
			}
			sev := "medium"
			if tag == "FIXME" || tag == "BUG" {
				sev = "high"
			}
			findings = append(findings, Finding{
				Type:        tag,
				Severity:    sev,
				File:        rel,
				Line:        lineNum,
				Description: desc,
			})
		}
		return nil
	})
	return findings, err
}

// applyFilter returns only findings at or above the requested severity level.
func applyFilter(findings []Finding, severity string) []Finding {
	if severity == "" || severity == "all" {
		return findings
	}
	cutoff := severityIndex(severity)
	if cutoff >= len(severityOrder) {
		return findings
	}
	out := findings[:0:0]
	for _, f := range findings {
		if severityIndex(f.Severity) <= cutoff {
			out = append(out, f)
		}
	}
	return out
}

// buildStaticReport generates a Markdown report from static findings only.
func buildStaticReport(repoRoot string, findings []Finding) string {
	repoName := filepath.Base(repoRoot)
	var b strings.Builder
	fmt.Fprintf(&b, "# REFACTOR.md — %s\n\n", repoName)
	b.WriteString("> Generated by `rekipedia refactor --no-llm` (static analysis only)\n\n")
	fmt.Fprintf(&b, "## Summary\n\n- **Repository**: `%s`\n- **Findings**: %d\n\n", repoRoot, len(findings))

	if len(findings) == 0 {
		b.WriteString("_No static annotations (TODO/FIXME/HACK/XXX) found._\n")
		return b.String()
	}

	b.WriteString("## Findings\n\n")
	b.WriteString("| Severity | Type | File | Line | Description |\n")
	b.WriteString("|----------|------|------|------|-------------|\n")
	for _, sev := range severityOrder {
		for _, f := range findings {
			if f.Severity != sev {
				continue
			}
			badge := severityEmoji[sev]
			fmt.Fprintf(&b, "| %s %s | `%s` | `%s` | %d | %s |\n",
				badge, strings.Title(sev), f.Type, f.File, f.Line, f.Description) //nolint:staticcheck
		}
	}
	b.WriteString("\n")
	return b.String()
}

var refactorCmd = &cobra.Command{
	Use:   "refactor [repo-path]",
	Short: "Static analysis + LLM suggestions to produce REFACTOR.md",
	Long: `Analyse the repository and produce a prioritised REFACTOR.md.

Two-phase pipeline:
  1. Static analysis  — scans source files for TODO/FIXME/HACK/XXX annotations.
  2. LLM enrichment   — feeds extracted symbols/relationships to the LLM for
                        a full technical-debt report (skipped with --no-llm).

Examples:
  rekipedia refactor .
  rekipedia refactor . --no-llm
  rekipedia refactor . --stdout | claude --context -
  rekipedia refactor . --severity high
  rekipedia refactor . --json`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		root := "."
		if len(args) > 0 {
			root = args[0]
		}
		absRoot, err := filepath.Abs(root)
		if err != nil {
			return fmt.Errorf("resolve path: %w", err)
		}

		outDir := outputDir
		if refactorFlags.outputDir != "" {
			outDir = refactorFlags.outputDir
		}

		if !refactorFlags.toStdout {
			pterm.DefaultHeader.
				WithFullWidth(false).
				WithBackgroundStyle(pterm.NewStyle(pterm.BgDarkGray)).
				WithTextStyle(pterm.NewStyle(pterm.FgWhite)).
				Println("rekipedia refactor ▸ " + absRoot)
		}

		// ── Static walk ────────────────────────────────────────────────
		findings, err := staticWalk(absRoot)
		if err != nil {
			return fmt.Errorf("static walk: %w", err)
		}

		sev := strings.ToLower(refactorFlags.severity)
		findings = applyFilter(findings, sev)

		// ── JSON output ────────────────────────────────────────────────
		if refactorFlags.outputJSON {
			payload := map[string]interface{}{
				"repo":     absRoot,
				"findings": findings,
			}
			data, err := json.MarshalIndent(payload, "", "  ")
			if err != nil {
				return err
			}
			if refactorFlags.toStdout {
				fmt.Println(string(data))
				return nil
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			outPath := filepath.Join(outDir, "REFACTOR.json")
			if err := os.WriteFile(outPath, data, 0o644); err != nil {
				return err
			}
			pterm.Success.Printf("REFACTOR.json written → %s\n", outPath)
			return nil
		}

		// ── Static-only report ─────────────────────────────────────────
		if refactorFlags.noLLM {
			report := buildStaticReport(absRoot, findings)
			if refactorFlags.toStdout {
				fmt.Print(report)
				return nil
			}
			if err := os.MkdirAll(outDir, 0o755); err != nil {
				return err
			}
			outPath := filepath.Join(outDir, "REFACTOR.md")
			if err := os.WriteFile(outPath, []byte(report), 0o644); err != nil {
				return err
			}
			pterm.Success.Printf("REFACTOR.md written → %s\n", outPath)
			return nil
		}

		// ── LLM-enriched report ────────────────────────────────────────
		// The Go implementation delegates to the static report for now; full
		// LLM enrichment via the orchestrator pipeline requires a completed
		// scan store and is invoked as a post-scan step (--with-refactor on
		// scan) or directly once RunRefactor is available in the orchestrator.
		pterm.Info.Println("LLM enrichment not yet available in the Go binary — falling back to static analysis.")
		pterm.Info.Println("Use the Python CLI (`rekipedia refactor .`) for full LLM-enriched output.")

		report := buildStaticReport(absRoot, findings)
		if refactorFlags.toStdout {
			fmt.Print(report)
			return nil
		}
		if err := os.MkdirAll(outDir, 0o755); err != nil {
			return err
		}
		repoName := filepath.Base(absRoot)
		// Prepend LLM note to the static report header
		llmNote := fmt.Sprintf(
			"# REFACTOR.md — %s\n\n> Generated by `rekipedia refactor` (Go, static analysis)\n\n",
			repoName,
		)
		// Replace duplicated header line from buildStaticReport
		report = strings.Replace(report, fmt.Sprintf("# REFACTOR.md — %s\n", repoName), "", 1)
		report = llmNote + strings.TrimLeft(report, "\n")

		outPath := filepath.Join(outDir, "REFACTOR.md")
		if err := os.WriteFile(outPath, []byte(report), 0o644); err != nil {
			return err
		}
		pterm.Success.Printf("REFACTOR.md written → %s\n", outPath)
		return nil
	},
}

func init() {
	refactorCmd.Flags().BoolVar(&refactorFlags.noLLM, "no-llm", false, "Static analysis only — skip LLM (fast, free)")
	refactorCmd.Flags().BoolVar(&refactorFlags.toStdout, "stdout", false, "Print REFACTOR.md to stdout instead of writing a file")
	refactorCmd.Flags().StringVar(&refactorFlags.severity, "severity", "all", "Only show issues at or above this level (all|critical|high|medium|low)")
	refactorCmd.Flags().BoolVar(&refactorFlags.outputJSON, "json", false, "Output findings as JSON")
	refactorCmd.Flags().StringVar(&refactorFlags.model, "model", "", "LLM model override")
	refactorCmd.Flags().StringVar(&refactorFlags.outputDir, "output-dir", "", "Output directory (default: .rekipedia)")
	refactorCmd.Flags().BoolVar(&refactorFlags.noDocker, "no-docker", false, "Skip Docker, run extractors in-process")
	refactorCmd.Flags().BoolVarP(&refactorFlags.verbose, "verbose", "v", false, "Verbose output")
	refactorCmd.Flags().StringVarP(&refactorFlags.languages, "languages", "l", "", "Comma-separated languages to analyse, e.g. python,go")
}
