"""rekipedia context — generate an agent-ready single-file context output.

Usage:
    rekipedia context [--repo PATH] [--output FILE] [--max-tokens N] [--output-dir DIR]
"""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path

import click
from rich.console import Console

console = Console()


@click.command("context")
@click.option(
    "--repo",
    default=".",
    show_default=True,
    type=click.Path(exists=True, file_okay=False),
    help="Root of the repository to read context from.",
)
@click.option(
    "--output",
    "-o",
    default="context.md",
    show_default=True,
    help="Destination file path for the context document.",
)
@click.option(
    "--max-tokens",
    default=32000,
    show_default=True,
    type=int,
    help="Maximum token budget (~4 chars per token). Output is truncated to fit.",
)
@click.option(
    "--output-dir",
    default=None,
    help="Path to .rekipedia/ directory (default: REPO/.rekipedia/).",
)
def context_cmd(
    repo: str,
    output: str,
    max_tokens: int,
    output_dir: str | None,
) -> None:
    """Generate an agent-ready single-file context document.

    \b
    Examples:
        rekipedia context
        rekipedia context --repo ./myproject --output ctx.md --max-tokens 16000
    """
    repo_path = Path(repo).resolve()
    reki_dir = Path(output_dir).resolve() if output_dir else repo_path / ".rekipedia"

    wiki_dir = reki_dir / "wiki"
    symbols_path = reki_dir / "exports" / "symbols.json"

    # ------------------------------------------------------------------ #
    # Build document sections                                              #
    # ------------------------------------------------------------------ #
    now = datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    sections: list[str] = []

    # Frontmatter
    sections.append(
        "---\n"
        f"generated_at: {now}\n"
        f"repo: {repo_path}\n"
        f"max_tokens: {max_tokens}\n"
        f"source: rekipedia context\n"
        "---\n\n"
    )

    sections.append(f"# rekipedia context: {repo_path.name}\n\n")
    sections.append(
        "> This document was generated by `rekipedia context` and is intended for "
        "use as a single-file context payload for AI agents.\n\n"
    )

    # Wiki pages
    wiki_pages: list[Path] = []
    if wiki_dir.exists():
        wiki_pages = sorted(wiki_dir.glob("*.md"))

    sections.append("## Wiki Pages\n\n")
    if wiki_pages:
        for page in wiki_pages:
            title = page.stem.replace("-", " ").title()
            content = page.read_text(encoding="utf-8").strip()
            sections.append(f"### {title}\n\n{content}\n\n---\n\n")
    else:
        sections.append("*No wiki pages found. Run `rekipedia scan` first.*\n\n")

    # Symbols
    sections.append("## Top Symbols\n\n")
    if symbols_path.exists():
        try:
            symbols_data = json.loads(symbols_path.read_text(encoding="utf-8"))
            symbols = symbols_data if isinstance(symbols_data, list) else symbols_data.get("symbols", [])
            # Show up to 100 symbols
            for sym in symbols[:100]:
                name = sym.get("name", "")
                kind = sym.get("kind", "")
                file_path = sym.get("file", "")
                doc = sym.get("docstring", "") or sym.get("doc", "") or ""
                line = f"- **{name}** `{kind}`"
                if file_path:
                    line += f" — `{file_path}`"
                if doc:
                    short_doc = doc.split("\n")[0][:120]
                    line += f"\n  > {short_doc}"
                sections.append(line + "\n")
            if len(symbols) > 100:
                sections.append(f"\n*…and {len(symbols) - 100} more symbols.*\n")
            sections.append("\n")
        except Exception as exc:
            sections.append(f"*Could not load symbols: {exc}*\n\n")
    else:
        sections.append("*No symbols export found. Run `rekipedia export` first.*\n\n")

    # ------------------------------------------------------------------ #
    # Truncate to max_tokens                                               #
    # ------------------------------------------------------------------ #
    max_chars = max_tokens * 4
    full_text = "".join(sections)
    if len(full_text) > max_chars:
        truncation_notice = (
            f"\n\n---\n*Context truncated to {max_tokens} tokens "
            f"({max_chars} chars). Total available: {len(full_text)} chars.*\n"
        )
        full_text = full_text[:max_chars - len(truncation_notice)] + truncation_notice

    # ------------------------------------------------------------------ #
    # Write output                                                         #
    # ------------------------------------------------------------------ #
    dest = Path(output)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(full_text, encoding="utf-8")

    size_kb = dest.stat().st_size / 1024
    token_estimate = len(full_text) // 4
    console.print(
        f"[green]✅ Context written[/green] → [bold]{dest}[/bold] "
        f"({size_kb:.1f} KB, ~{token_estimate:,} tokens)"
    )
    console.print(f"   wiki pages : {len(wiki_pages)}")
