"""`rekipedia init` command — scaffold the .rekipedia/ bundle in a repo."""
from __future__ import annotations

from pathlib import Path

import click
from rich.console import Console

console = Console()

_DEFAULT_CONFIG_YAML = """\
# Project-level config — overrides ~/.config/rekipedia/config.yml
# rekipedia configuration — .rekipedia/config.yml
# Run `reki init` to regenerate this file.
version: 1

# ── Files to ignore (gitignore-style patterns) ───────────────────────────────
ignore:
  - .git
  - node_modules
  - __pycache__
  - .rekipedia

# ── Language filter ───────────────────────────────────────────────────────────
# Controls which source files are scanned.
#
# Supported values:
#   python, typescript, javascript, go, rust, java, kotlin, ruby,
#   markdown, yaml, json, toml, sql, shell, docker, terraform, html, css, scss
#
# Set to `null` (or remove the key) to scan ALL supported languages — recommended
# for mixed-language repos (e.g. Python + Go).
#
# Examples:
#   languages: null           # scan everything (DEFAULT)
#   languages: [python]       # Python only
#   languages: [python, go]   # Python + Go
#   languages: [typescript, javascript, go]
#
languages:   # null = all languages

# ── LLM settings ─────────────────────────────────────────────────────────────
llm:
  # Model in litellm format: provider/model-name  (can override per-project)
  # Examples:
  #   ollama/llama4          (local Ollama — default)
  #   openai/gpt-4o
  #   anthropic/claude-sonnet-4
  #   openrouter/google/gemini-2.5-pro
  # model: ollama/llama4
  model: ollama/llama4
  # api_key, base_url, embed_api_key, embed_base_url — set in global config
  # (~/.config/rekipedia/config.yml) or via env vars (REKIPEDIA_API_KEY, etc.)
  temperature: 0.2

  # ── Embedding model (for semantic search / RAG) ───────────────────────────
  # Leave blank to use the same model as above (not recommended for large repos).
  # embed_model: text-embedding-3-small
  # embed_provider: openai
"""

_GITIGNORE_ENTRY = ".rekipedia/store.db\n"

_GH_ACTIONS_TEMPLATE = """\
# .github/workflows/rekipedia-wiki.yml
# Auto-generated by `reki init --with-ci`
#
# Scans the codebase and publishes a fresh wiki to docs/wiki/ on every push
# to main.  Set the REKIPEDIA_API_KEY repository secret for LLM-enriched pages;
# omit it to run in --no-llm (symbol-only) mode.

name: rekipedia wiki

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install rekipedia
        run: pip install rekipedia

      - name: Scan codebase
        env:
          REKIPEDIA_API_KEY: ${{ secrets.REKIPEDIA_API_KEY }}
        run: |
          if [ -n "$REKIPEDIA_API_KEY" ]; then
            reki scan .
          else
            echo "REKIPEDIA_API_KEY not set — running in --no-llm mode"
            reki scan . --no-llm
          fi

      - name: Publish wiki to docs/wiki/
        run: |
          mkdir -p docs/wiki
          reki publish . --output-dir docs/wiki/ --force

      - name: Commit and push wiki changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/wiki/
          if git diff --cached --quiet; then
            echo "No wiki changes — nothing to commit."
          else
            git commit -m "chore: update rekipedia wiki [skip ci]"
            git push
"""

_AGENT_CONTENT_TEMPLATE = """\
# rekipedia — AI Codebase Intelligence

This repository uses [rekipedia](https://github.com/unrealandychan/rekipedia) to maintain a structured wiki and answer questions about the codebase.

## Available commands

| Command | What it does |
|---------|-------------|
| `reki scan .` | Full scan — extract symbols, generate wiki pages, build knowledge store |
| `reki update .` | Incremental refresh — only re-processes changed files |
| `reki ask "<question>"` | Ask anything about the codebase — grounded answers with file:line citations |
| `reki serve .` | Start local web UI at http://127.0.0.1:7070 to browse wiki & ask questions |
| `reki embed .` | Build / rebuild the semantic search index (FAISS) for hybrid RAG |
| `reki export .` | Export wiki to a single file (--format md|zip|json) |

## When to use rekipedia

- Before answering questions about the codebase architecture, run `reki ask "<your question>"` to get grounded context
- After making significant changes, run `reki update .` to keep the wiki current
- When asked to understand how a feature works, check the wiki first with `reki ask`
- When onboarding to an unfamiliar part of the codebase, use `reki ask` for guided explanation

## Setup (first time)

```bash
reki scan .          # generates the wiki and knowledge store
reki embed .         # builds semantic search index (optional, for RAG)
```

The knowledge store lives in `.rekipedia/store.db` — portable, local, no cloud required.
"""


def _write_github_actions(repo_path: Path, force: bool = False) -> None:
    """Write the GitHub Actions workflow that keeps the wiki up-to-date."""
    workflow_path = repo_path / ".github" / "workflows" / "rekipedia-wiki.yml"

    if workflow_path.exists() and not force:
        console.print(
            f"[yellow]⚠[/yellow]  [bold]{workflow_path}[/bold] already exists — skipping."
        )
        return

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    workflow_path.write_text(_GH_ACTIONS_TEMPLATE, encoding="utf-8")
    console.print(
        f"[green]✔[/green]  Created [bold]{workflow_path}[/bold] (GitHub Actions CI)"
    )


def _write_agent_files(repo_path: Path, force: bool = False) -> None:
    """Write agent instruction files for Claude Code, Codex/OpenAI, and GitHub Copilot."""
    files = [
        (repo_path / "CLAUDE.md", "Claude Code"),
        (repo_path / "AGENTS.md", "Codex / OpenAI Agents"),
        (repo_path / ".github" / "copilot-instructions.md", "GitHub Copilot"),
    ]
    for file_path, platform in files:
        if file_path.exists() and not force:
            console.print(
                f"[yellow]⚠[/yellow]  [bold]{file_path}[/bold] already exists — skipping."
            )
        else:
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(_AGENT_CONTENT_TEMPLATE, encoding="utf-8")
            console.print(f"[green]✔[/green]  Created [bold]{file_path}[/bold] ({platform})")


_GITATTRIBUTES_LINES = (
    ".rekipedia/wiki/*.md merge=reki-wiki\n"
    "docs/wiki/*.md       merge=reki-wiki\n"
)


def _setup_merge_driver(repo_path: Path) -> None:
    """Write .gitattributes entries and register git merge driver in .git/config."""
    import subprocess

    gitattributes_path = repo_path / ".gitattributes"
    if gitattributes_path.exists():
        existing = gitattributes_path.read_text(encoding="utf-8")
        if "merge=reki-wiki" in existing:
            console.print(
                "[yellow]⚠[/yellow]  .gitattributes already contains merge=reki-wiki entries — skipping."
            )
        else:
            with gitattributes_path.open("a", encoding="utf-8") as fh:
                fh.write(_GITATTRIBUTES_LINES)
            console.print("[green]✔[/green]  Added merge=reki-wiki entries to .gitattributes")
    else:
        gitattributes_path.write_text(_GITATTRIBUTES_LINES, encoding="utf-8")
        console.print("[green]✔[/green]  Created .gitattributes with merge=reki-wiki entries")

    git_config_cmds = [
        ["git", "config", "merge.reki-wiki.name", "rekipedia wiki merge driver"],
        ["git", "config", "merge.reki-wiki.driver", "reki merge-driver %O %A %B"],
        ["git", "config", "merge.reki-wiki.recursive", "binary"],
    ]
    for cmd in git_config_cmds:
        result = subprocess.run(cmd, cwd=repo_path, capture_output=True, text=True)
        if result.returncode != 0:
            console.print(f"[red]✗[/red]  git config failed: {result.stderr.strip()}")
        else:
            console.print(f"[green]✔[/green]  Ran: {' '.join(cmd[2:])}")

    console.print()
    console.print(
        "  [dim]Tip: commit [bold].gitattributes[/bold] so teammates get the merge driver.\n"
        "  [bold].git/config[/bold] is local-only and not committed.[/dim]"
    )


def run_init(repo_path: Path, no_agent_files: bool = False, with_ci: bool = False, with_merge_driver: bool = False) -> None:
    wiki_dir = repo_path / ".rekipedia"
    config_path = wiki_dir / "config.yml"
    gitignore_path = repo_path / ".gitignore"

    # Create .rekipedia/ if missing
    wiki_dir.mkdir(parents=True, exist_ok=True)

    # Write config.yml — idempotent (skip if already present)
    if config_path.exists():
        console.print(
            f"[yellow]⚠[/yellow]  [bold]{config_path}[/bold] already exists — skipping."
        )
    else:
        config_path.write_text(
            _DEFAULT_CONFIG_YAML,
            encoding="utf-8",
        )
        console.print(f"[green]✔[/green]  Created [bold]{config_path}[/bold]")

    # Append .gitignore entry — idempotent
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
        if ".rekipedia/store.db" in existing:
            console.print(
                "[yellow]⚠[/yellow]  .gitignore already contains .rekipedia/store.db — skipping."
            )
        else:
            with gitignore_path.open("a", encoding="utf-8") as fh:
                fh.write(_GITIGNORE_ENTRY)
            console.print("[green]✔[/green]  Added .rekipedia/store.db to .gitignore")
    else:
        gitignore_path.write_text(_GITIGNORE_ENTRY, encoding="utf-8")
        console.print("[green]✔[/green]  Created .gitignore with .rekipedia/store.db")

    if not no_agent_files:
        console.print()
        console.print("[bold]Writing agent instruction files…[/bold]")
        _write_agent_files(repo_path)

    if with_ci:
        console.print()
        console.print("[bold]Writing GitHub Actions workflow…[/bold]")
        _write_github_actions(repo_path)

    if with_merge_driver:
        console.print()
        console.print("[bold]Setting up git merge driver…[/bold]")
        _setup_merge_driver(repo_path)

    console.print()
    console.print("[bold green]rekipedia initialised.[/bold green]")
    console.print(
        f"  Edit [cyan]{config_path}[/cyan] to choose your LLM provider/model, then run:"
    )
    console.print("  [bold]rekipedia scan .[/bold]")
    if with_ci:
        console.print()
        console.print(
            "  [dim]Tip: set the [bold]REKIPEDIA_API_KEY[/bold] repository secret in GitHub "
            "for LLM-enriched wiki pages. Without it the workflow runs in --no-llm mode.[/dim]"
        )


@click.command("init")
@click.argument(
    "repo",
    default=".",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
)
@click.option(
    "--no-agent-files",
    is_flag=True,
    default=False,
    help="Skip writing CLAUDE.md, AGENTS.md, and .github/copilot-instructions.md.",
)
@click.option(
    "--with-ci",
    is_flag=True,
    default=False,
    help=(
        "Write .github/workflows/rekipedia-wiki.yml — a GitHub Actions workflow that "
        "scans the repo and publishes the wiki to docs/wiki/ on every push to main. "
        "Uses the REKIPEDIA_API_KEY secret when present; falls back to --no-llm otherwise."
    ),
)
@click.option(
    "--with-merge-driver",
    is_flag=True,
    default=False,
    help=(
        "Register reki-wiki as a git merge driver and write .gitattributes entries "
        "for wiki markdown files. .gitattributes should be committed; .git/config is local-only."
    ),
)
def init_cmd(repo: Path, no_agent_files: bool, with_ci: bool, with_merge_driver: bool) -> None:
    """Initialise rekipedia in REPO (default: current directory)."""
    run_init(repo.resolve(), no_agent_files=no_agent_files, with_ci=with_ci, with_merge_driver=with_merge_driver)
