"""`rekipedia init` command — scaffold the .rekipedia/ bundle in a repo."""
from __future__ import annotations

import json
from pathlib import Path

import click
from rich.console import Console

console = Console()

_DEFAULT_CONFIG_YAML = """\
# Project-level config — overrides ~/.config/rekipedia/config.yml
# rekipedia configuration — .rekipedia/config.yml
# Run `reki init` to regenerate this file.
version: 1

# ── Files to ignore (gitignore-style patterns) ───────────────────────────────
ignore:
  - .git
  - node_modules
  - __pycache__
  - .rekipedia

# ── Language filter ───────────────────────────────────────────────────────────
# Controls which source files are scanned.
#
# Supported values:
#   python, typescript, javascript, go, rust, java, kotlin, ruby,
#   markdown, yaml, json, toml, sql, shell, docker, terraform, html, css, scss
#
# Set to `null` (or remove the key) to scan ALL supported languages — recommended
# for mixed-language repos (e.g. Python + Go).
#
# Examples:
#   languages: null           # scan everything (DEFAULT)
#   languages: [python]       # Python only
#   languages: [python, go]   # Python + Go
#   languages: [typescript, javascript, go]
#
languages:   # null = all languages

# ── LLM settings ─────────────────────────────────────────────────────────────
llm:
  # Model in litellm format: provider/model-name  (can override per-project)
  # Examples:
  #   ollama/llama4          (local Ollama — default)
  #   openai/gpt-4o
  #   anthropic/claude-sonnet-4
  #   openrouter/google/gemini-2.5-pro
  # model: ollama/llama4
  model: ollama/llama4
  # api_key, base_url, embed_api_key, embed_base_url — set in global config
  # (~/.config/rekipedia/config.yml) or via env vars (REKIPEDIA_API_KEY, etc.)
  temperature: 0.2

  # ── Embedding model (for semantic search / RAG) ───────────────────────────
  # Leave blank to use the same model as above (not recommended for large repos).
  # embed_model: text-embedding-3-small
  # embed_provider: openai
"""

_GITIGNORE_ENTRY = ".rekipedia/store.db\n"

_GH_ACTIONS_TEMPLATE = """\
# .github/workflows/rekipedia-wiki.yml
# Auto-generated by `reki init --with-ci`
#
# Scans the codebase and publishes a fresh wiki to docs/wiki/ on every push
# to main.  Set the REKIPEDIA_API_KEY repository secret for LLM-enriched pages;
# omit it to run in --no-llm (symbol-only) mode.

name: rekipedia wiki

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install rekipedia
        run: pip install rekipedia

      - name: Scan codebase
        env:
          REKIPEDIA_API_KEY: ${{ secrets.REKIPEDIA_API_KEY }}
        run: |
          if [ -n "$REKIPEDIA_API_KEY" ]; then
            reki scan .
          else
            echo "REKIPEDIA_API_KEY not set — running in --no-llm mode"
            reki scan . --no-llm
          fi

      - name: Publish wiki to docs/wiki/
        run: |
          mkdir -p docs/wiki
          reki publish . --output-dir docs/wiki/ --force

      - name: Commit and push wiki changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/wiki/
          if git diff --cached --quiet; then
            echo "No wiki changes — nothing to commit."
          else
            git commit -m "chore: update rekipedia wiki [skip ci]"
            git push
"""

_GH_ACTIONS_TEMPLATE_S3_UPLOAD_STEP = """\
      # Upload wiki bundle to S3 (requires AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY secrets
      # and REKIPEDIA_S3_BUCKET repository variable)
      - name: Upload wiki bundle to S3
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          reki export --format bundle --output /tmp/wiki-bundle/
          cd /tmp/wiki-bundle && zip -r wiki-bundle.zip .
          aws s3 cp wiki-bundle.zip s3://${{ vars.REKIPEDIA_S3_BUCKET }}/wiki-bundle.zip
"""

_GH_ACTIONS_TEMPLATE_GCS_UPLOAD_STEP = """\
      # Upload wiki bundle to GCS (requires GCP_CREDENTIALS secret (base64 service account JSON)
      # and REKIPEDIA_GCS_BUCKET repository variable)
      - name: Upload wiki bundle to GCS
        if: github.ref == 'refs/heads/main'
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDENTIALS" | base64 -d > /tmp/gcp-creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-creds.json
          reki export --format bundle --output /tmp/wiki-bundle/
          cd /tmp/wiki-bundle && zip -r wiki-bundle.zip .
          gsutil cp wiki-bundle.zip gs://${{ vars.REKIPEDIA_GCS_BUCKET }}/wiki-bundle.zip
"""

_CLAUDE_MD_TEMPLATE = """\
# rekipedia — AI Codebase Intelligence

This repository uses [rekipedia](https://github.com/unrealandychan/rekipedia) to maintain a structured wiki and knowledge store.

## MCP server (recommended)

rekipedia exposes an MCP server — use it before reading source files:

```json
// .mcp.json is already configured at the repo root
```

Available MCP tools: `ask`, `search_nodes`, `get_context`, `get_relationships`, `get_hub_nodes`, `get_impact`, `get_knowledge_gaps`, `list_wiki_pages`, `get_wiki_page`

## CLI fallback

```bash
reki ask "<question>"      # grounded Q&A with file:line citations
reki search "<symbol>"     # symbol lookup
reki scan .                # full rescan after big changes
reki update .              # incremental refresh
```

## Rules

- Always call `ask` MCP tool (or `reki ask`) BEFORE reading source files
- After significant changes, run `reki update .` to keep the wiki current
"""

_AGENTS_MD_TEMPLATE = """\
# rekipedia — AI Codebase Intelligence

This repository uses [rekipedia](https://github.com/unrealandychan/rekipedia) to maintain a structured wiki and knowledge store.

## MCP server

rekipedia runs as an MCP server. Configure in `~/.codex/config.toml`:

```toml
[[mcp_servers]]
name = "rekipedia"
command = ["reki", "mcp"]
```

Available MCP tools: `ask`, `search_nodes`, `get_context`, `get_relationships`, `get_hub_nodes`, `get_impact`, `get_knowledge_gaps`, `list_wiki_pages`, `get_wiki_page`

## CLI fallback

```bash
reki ask "<question>"      # grounded Q&A with file:line citations
reki search "<symbol>"     # symbol lookup
reki scan .                # full rescan after big changes
reki update .              # incremental refresh
```

## Rules

- Always call `ask` MCP tool (or `reki ask`) BEFORE reading source files
- After significant changes, run `reki update .` to keep the wiki current
"""

_COPILOT_INSTRUCTIONS_TEMPLATE = """\
# rekipedia — AI Codebase Intelligence

This repository uses [rekipedia](https://github.com/unrealandychan/rekipedia) to maintain a structured wiki and knowledge store.

## MCP server (VS Code Copilot)

rekipedia is configured as an MCP server in `.vscode/mcp.json`. Use MCP tools before reading source files:

Available tools: `ask`, `search_nodes`, `get_context`, `get_relationships`, `get_hub_nodes`, `get_impact`, `get_knowledge_gaps`, `list_wiki_pages`, `get_wiki_page`

## When to use rekipedia

- Before answering architecture questions — use `ask`
- Before editing a file — use `get_context` to understand its symbols
- After the user asks how a feature works — use `ask` first
- To understand what breaks if a file changes — use `get_impact`

## CLI

```bash
reki ask "<question>"
reki search "<symbol>"
reki update .
```
"""

_VSCODE_MCP_JSON = {
    "servers": {
        "rekipedia": {
            "type": "stdio",
            "command": "reki",
            "args": ["mcp"],
            "description": "rekipedia codebase knowledge — ask questions, search symbols, get impact analysis",
        }
    }
}

_CURSOR_MCP_JSON = {
    "mcpServers": {
        "rekipedia": {
            "command": "reki",
            "args": ["mcp"],
            "description": "rekipedia codebase knowledge — ask questions, search symbols, get impact analysis",
        }
    }
}

_CURSOR_RULES_MDC = """\
---
description: Use rekipedia MCP tools before reading source files
alwaysApply: true
---

# rekipedia codebase intelligence

Always use rekipedia MCP tools before reading source files or answering architecture questions.

Available tools: `ask`, `search_nodes`, `get_context`, `get_relationships`, `get_hub_nodes`, `get_impact`, `get_knowledge_gaps`, `list_wiki_pages`, `get_wiki_page`

- Use `ask` for any natural-language question about the codebase
- Use `get_context` before editing any file
- Use `get_impact` before refactoring
"""

_CODEX_MCP_HINT_MD = """\
# rekipedia MCP server — Codex CLI setup

Add the following to `~/.codex/config.toml` to enable rekipedia in Codex CLI:

```toml
[[mcp_servers]]
name = "rekipedia"
command = ["reki", "mcp"]
```

Available MCP tools: `ask`, `search_nodes`, `get_context`, `get_relationships`,
`get_hub_nodes`, `get_impact`, `get_knowledge_gaps`, `list_wiki_pages`, `get_wiki_page`
"""


def _write_github_actions(repo_path: Path, force: bool = False, with_upload: str | None = None) -> None:
    """Write the GitHub Actions workflow that keeps the wiki up-to-date."""
    workflow_path = repo_path / ".github" / "workflows" / "rekipedia-wiki.yml"

    if workflow_path.exists() and not force:
        console.print(
            f"[yellow]⚠[/yellow]  [bold]{workflow_path}[/bold] already exists — skipping."
        )
        return

    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    content = _GH_ACTIONS_TEMPLATE
    if with_upload == "s3":
        content += _GH_ACTIONS_TEMPLATE_S3_UPLOAD_STEP
    elif with_upload == "gcs":
        content += _GH_ACTIONS_TEMPLATE_GCS_UPLOAD_STEP
    workflow_path.write_text(content, encoding="utf-8")
    console.print(
        f"[green]✔[/green]  Created [bold]{workflow_path}[/bold] (GitHub Actions CI)"
    )


def _write_agent_files(repo_path: Path, force: bool = False) -> None:
    """Write agent instruction files for Claude Code, Codex/OpenAI, and GitHub Copilot."""
    files = [
        (repo_path / "CLAUDE.md", "Claude Code", _CLAUDE_MD_TEMPLATE),
        (repo_path / "AGENTS.md", "Codex / OpenAI Agents", _AGENTS_MD_TEMPLATE),
        (repo_path / ".github" / "copilot-instructions.md", "GitHub Copilot", _COPILOT_INSTRUCTIONS_TEMPLATE),
    ]
    for file_path, platform, template in files:
        if file_path.exists() and not force:
            console.print(
                f"[yellow]⚠[/yellow]  [bold]{file_path}[/bold] already exists — skipping."
            )
        else:
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(template, encoding="utf-8")
            console.print(f"[green]✔[/green]  Created [bold]{file_path}[/bold] ({platform})")


def _write_copilot_files(repo_path: Path) -> None:
    """Write .vscode/mcp.json and update .vscode/settings.json for GitHub Copilot."""
    vscode_dir = repo_path / ".vscode"
    vscode_dir.mkdir(parents=True, exist_ok=True)

    mcp_path = vscode_dir / "mcp.json"
    mcp_path.write_text(json.dumps(_VSCODE_MCP_JSON, indent=2) + "\n", encoding="utf-8")
    console.print("[green]✔[/green]  Created .vscode/mcp.json (GitHub Copilot MCP)")

    settings_path = vscode_dir / "settings.json"
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            settings = {}
    else:
        settings = {}
    settings["chat.mcp.enabled"] = True
    settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
    console.print("[green]✔[/green]  Updated .vscode/settings.json (chat.mcp.enabled: true)")


def _write_codex_files(repo_path: Path) -> None:
    """Write codex-mcp-hint.md and .codex/instructions.md for Codex CLI."""
    hint_path = repo_path / "codex-mcp-hint.md"
    hint_path.write_text(_CODEX_MCP_HINT_MD, encoding="utf-8")
    console.print("[green]✔[/green]  Created codex-mcp-hint.md (Codex CLI MCP setup instructions)")

    codex_dir = repo_path / ".codex"
    codex_dir.mkdir(parents=True, exist_ok=True)
    instructions_path = codex_dir / "instructions.md"
    instructions_path.write_text(_AGENTS_MD_TEMPLATE, encoding="utf-8")
    console.print("[green]✔[/green]  Created .codex/instructions.md (Codex agent instructions)")


def _write_cursor_files(repo_path: Path) -> None:
    """Write .cursor/mcp.json and .cursor/rules/rekipedia.mdc for Cursor."""
    cursor_dir = repo_path / ".cursor"
    cursor_dir.mkdir(parents=True, exist_ok=True)

    mcp_path = cursor_dir / "mcp.json"
    mcp_path.write_text(json.dumps(_CURSOR_MCP_JSON, indent=2) + "\n", encoding="utf-8")
    console.print("[green]✔[/green]  Created .cursor/mcp.json (Cursor MCP)")

    rules_dir = cursor_dir / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    rules_path = rules_dir / "rekipedia.mdc"
    rules_path.write_text(_CURSOR_RULES_MDC, encoding="utf-8")
    console.print("[green]✔[/green]  Created .cursor/rules/rekipedia.mdc (Cursor rules)")


_GITATTRIBUTES_LINES = (
    ".rekipedia/wiki/*.md merge=reki-wiki\n"
    "docs/wiki/*.md       merge=reki-wiki\n"
)


def _setup_merge_driver(repo_path: Path) -> None:
    """Write .gitattributes entries and register git merge driver in .git/config."""
    import subprocess

    gitattributes_path = repo_path / ".gitattributes"
    if gitattributes_path.exists():
        existing = gitattributes_path.read_text(encoding="utf-8")
        if "merge=reki-wiki" in existing:
            console.print(
                "[yellow]⚠[/yellow]  .gitattributes already contains merge=reki-wiki entries — skipping."
            )
        else:
            with gitattributes_path.open("a", encoding="utf-8") as fh:
                fh.write(_GITATTRIBUTES_LINES)
            console.print("[green]✔[/green]  Added merge=reki-wiki entries to .gitattributes")
    else:
        gitattributes_path.write_text(_GITATTRIBUTES_LINES, encoding="utf-8")
        console.print("[green]✔[/green]  Created .gitattributes with merge=reki-wiki entries")

    git_config_cmds = [
        ["git", "config", "merge.reki-wiki.name", "rekipedia wiki merge driver"],
        ["git", "config", "merge.reki-wiki.driver", "reki merge-driver %O %A %B"],
        ["git", "config", "merge.reki-wiki.recursive", "binary"],
    ]
    for cmd in git_config_cmds:
        result = subprocess.run(cmd, cwd=repo_path, capture_output=True, text=True)
        if result.returncode != 0:
            console.print(f"[red]✗[/red]  git config failed: {result.stderr.strip()}")
        else:
            console.print(f"[green]✔[/green]  Ran: {' '.join(cmd[2:])}")

    console.print()
    console.print(
        "  [dim]Tip: commit [bold].gitattributes[/bold] so teammates get the merge driver.\n"
        "  [bold].git/config[/bold] is local-only and not committed.[/dim]"
    )


def run_init(  # noqa: C901
    repo_path: Path,
    no_agent_files: bool = False,
    with_ci: bool = False,
    with_merge_driver: bool = False,
    with_upload: str | None = None,
    with_copilot: bool = False,
    with_codex: bool = False,
    with_cursor: bool = False,
    with_all_ai: bool = False,
) -> None:
    if with_all_ai:
        with_copilot = True
        with_codex = True
        with_cursor = True

    wiki_dir = repo_path / ".rekipedia"
    config_path = wiki_dir / "config.yml"
    gitignore_path = repo_path / ".gitignore"

    # Create .rekipedia/ if missing
    wiki_dir.mkdir(parents=True, exist_ok=True)

    # Write config.yml — idempotent (skip if already present)
    if config_path.exists():
        console.print(
            f"[yellow]⚠[/yellow]  [bold]{config_path}[/bold] already exists — skipping."
        )
    else:
        config_path.write_text(
            _DEFAULT_CONFIG_YAML,
            encoding="utf-8",
        )
        console.print(f"[green]✔[/green]  Created [bold]{config_path}[/bold]")

    # Append .gitignore entry — idempotent
    if gitignore_path.exists():
        existing = gitignore_path.read_text(encoding="utf-8")
        if ".rekipedia/store.db" in existing:
            console.print(
                "[yellow]⚠[/yellow]  .gitignore already contains .rekipedia/store.db — skipping."
            )
        else:
            with gitignore_path.open("a", encoding="utf-8") as fh:
                fh.write(_GITIGNORE_ENTRY)
            console.print("[green]✔[/green]  Added .rekipedia/store.db to .gitignore")
    else:
        gitignore_path.write_text(_GITIGNORE_ENTRY, encoding="utf-8")
        console.print("[green]✔[/green]  Created .gitignore with .rekipedia/store.db")

    if not no_agent_files:
        console.print()
        console.print("[bold]Writing agent instruction files…[/bold]")
        _write_agent_files(repo_path)

    if with_ci:
        console.print()
        console.print("[bold]Writing GitHub Actions workflow…[/bold]")
        _write_github_actions(repo_path, with_upload=with_upload)

    if with_merge_driver:
        console.print()
        console.print("[bold]Setting up git merge driver…[/bold]")
        _setup_merge_driver(repo_path)

    if with_copilot:
        console.print()
        console.print("[bold]Writing GitHub Copilot files…[/bold]")
        _write_copilot_files(repo_path)

    if with_codex:
        console.print()
        console.print("[bold]Writing Codex CLI files…[/bold]")
        _write_codex_files(repo_path)

    if with_cursor:
        console.print()
        console.print("[bold]Writing Cursor files…[/bold]")
        _write_cursor_files(repo_path)

    console.print()
    console.print("[bold green]rekipedia initialised.[/bold green]")
    console.print(
        f"  Edit [cyan]{config_path}[/cyan] to choose your LLM provider/model, then run:"
    )
    console.print("  [bold]rekipedia scan .[/bold]")
    if with_ci:
        console.print()
        console.print(
            "  [dim]Tip: set the [bold]REKIPEDIA_API_KEY[/bold] repository secret in GitHub "
            "for LLM-enriched wiki pages. Without it the workflow runs in --no-llm mode.[/dim]"
        )


@click.command("init")
@click.argument(
    "repo",
    default=".",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
)
@click.option(
    "--no-agent-files",
    is_flag=True,
    default=False,
    help="Skip writing CLAUDE.md, AGENTS.md, and .github/copilot-instructions.md.",
)
@click.option(
    "--with-ci",
    is_flag=True,
    default=False,
    help=(
        "Write .github/workflows/rekipedia-wiki.yml — a GitHub Actions workflow that "
        "scans the repo and publishes the wiki to docs/wiki/ on every push to main. "
        "Uses the REKIPEDIA_API_KEY secret when present; falls back to --no-llm otherwise."
    ),
)
@click.option(
    "--with-merge-driver",
    is_flag=True,
    default=False,
    help=(
        "Register reki-wiki as a git merge driver and write .gitattributes entries "
        "for wiki markdown files. .gitattributes should be committed; .git/config is local-only."
    ),
)
@click.option(
    "--with-upload",
    type=click.Choice(["s3", "gcs"]),
    default=None,
    help="Add bundle upload step to CI workflow (s3 or gcs)",
)
@click.option(
    "--with-copilot",
    is_flag=True,
    default=False,
    help="Write .vscode/mcp.json and update .vscode/settings.json for GitHub Copilot.",
)
@click.option(
    "--with-codex",
    is_flag=True,
    default=False,
    help="Write codex-mcp-hint.md and .codex/instructions.md for Codex CLI.",
)
@click.option(
    "--with-cursor",
    is_flag=True,
    default=False,
    help="Write .cursor/mcp.json and .cursor/rules/rekipedia.mdc for Cursor.",
)
@click.option(
    "--with-all-ai",
    is_flag=True,
    default=False,
    help="Enable all AI tool integrations: --with-copilot, --with-codex, --with-cursor.",
)
def init_cmd(
    repo: Path,
    no_agent_files: bool,
    with_ci: bool,
    with_merge_driver: bool,
    with_upload: str | None,
    with_copilot: bool,
    with_codex: bool,
    with_cursor: bool,
    with_all_ai: bool,
) -> None:
    """Initialise rekipedia in REPO (default: current directory)."""
    if with_upload and not with_ci:
        from rich import print as rprint
        rprint("[red]Error:[/] --with-upload requires --with-ci")
        return
    run_init(
        repo.resolve(),
        no_agent_files=no_agent_files,
        with_ci=with_ci,
        with_merge_driver=with_merge_driver,
        with_upload=with_upload,
        with_copilot=with_copilot,
        with_codex=with_codex,
        with_cursor=with_cursor,
        with_all_ai=with_all_ai,
    )
